sudo: required
services:
  - docker
  - redis-server

before_install:
  - sudo service redis-server start --bind 127.0.0.1
  - docker build -t rafaelpsantos/ola-adeus-back -f Dockerfile.dev .

script:
  - docker run -e REDIS_HOST='127.0.0.1' rafaelpsantos/ola-adeus-back npm test -- --coverage