language: node_js

services:
  - redis
  - mongodb
  - docker

before_install:
  - make build

before_script:
  - sleep 30
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - sleep 30

script:
  - make test