sudo: required
services:
  - docker
  - redis-server

before_install:
  - docker build -t rafaelpsantos/ola-adeus-back -f Dockerfile.dev .

script:
  - docker run rafaelpsantos/ola-adeus-back npm test -- --coverage