sudo: required
services:
  - docker
  - redis-server

before_install:
  - docker build -t rafaelpsantos/ola-adeus-back -f Dockerfile.dev .

script:
  - docker run -e PORT=3000 -e SESSION_SECRET='password' -e REDIS_HOST='172.21.0.2' -e REDIS_PORT=6379 rafaelpsantos/ola-adeus-back npm test -- --coverage